version: '3'
services:
    dev:
        build:
            context: .
        ports:
            - 3030:3030
        volumes:
            - .:/app
    prod:
        build:
            context: .
            dockerfile: Dockefile_prod
        ports:
            - 3030:3030
